[package]
name = "nom_stl"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[features]
fx = ["rustc-hash"]
na = ["nalgebra"]
default = []

[dependencies]
nom = "5.0"
rustc-hash = { version = "1.0", optional = true }
nalgebra = { version = "0.18", optional = true }

[dev-dependencies]
criterion = "0.2"
memmap = "0.7"
quickcheck = "0.9"
quickcheck_macros = "0.8"

[[bench]]
name = "bench"
harness = false
