[package]
name = "nom_stl"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
hashbrown = { version = "0.5", optional = true }
nom = "5.0.0-beta1"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
